### ISSUE TITLE
Tags always include branch

### ISSUE THREAD

**Issue by gbaeke** [crazy-max/ghaction-docker-meta#12]
#### Steps to reproduce this issue

I use the following:

```yml
name: Docker meta
id: docker_meta
uses: crazy-max/ghaction-docker-meta@v1
with:
  images: user/repo
  tag-sha: true
```

     
#### Expected behaviour

Only have a user/repo:tag-sha in the outputs.tags

#### Actual behaviour

outputs.tags contains

user/repo:main
user/repo:tag-sha

Is this the expected behavior? If it is, can the branch tag be removed with a simple setting and without resorting to filtering the output? Sorry if I missed something obvious! 😉

**Comment by NatsumiHB** [comment]
I'm having the same issue. Also, in addition to that, I have no idea how I can get this workflow to use the latest git tag to tag since I want my images to be tagged with `latest` and `v.A.B.C` (where A, B and C are respective numbers).

**Comment by crazy-max** [comment]
@gbaeke 

> Only have a user/repo:tag-sha in the outputs.tags

If you only want the commit id as a tag then the `outputs.tag` might not be necessary. Instead you can do `tags: name/app:${{ github.sha }}`:

```yaml
name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          tags: name/app:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
```
