### ISSUE TITLE
Convert repo name to lower case.

### ISSUE THREAD

**Issue by krasi-georgiev** [crazy-max/ghaction-docker-meta#16]
```
-
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}
```

and when the repo name container upper case it fails to push. It would be nice to convert it all to lower case
