### ISSUE TITLE
Proposal: Redesign tagging input/outputs to be independent

### ISSUE THREAD

**Issue by LongLiveCHIEF** [crazy-max/ghaction-docker-meta#30]
I still use this action for labeling features, but if you're open to it, I'd really like you to consider importing my actions tag handling capabilities due to their power, simplicity, and flexibility.

To give you an example, here's a snippet from a repo where I'm using the latest functionality I've implemented, snippet pulled from https://github.com/OctoPrint/octoprint-docker/blob/master/.github/workflows/octoprint-release.yml#L69-L87:

```yaml
      -
        id: buildxy
        run: echo '::set-output name=buildxy::${{ (github.event.action == 'deploy'|| github.event.action == 'released') && github.event.client_payload.tag_name == steps.stable-octoprint.outputs.release }}'
      -
        name: Tagging Strategy
        id: tagging
        uses: HackerHappyHour/tagging-strategy@v3
        with:
          image_name: octoprint/octoprint
          tag_name: ${{ github.event.client_payload.tag_name }}
          tags: |
            %X%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y.Z%
          extra_tags: |
            latest::${{ steps.stable-octoprint.outputs.release == github.event.client_payload.tag_name }}
            edge::${{ github.event.action == 'prereleased' || github.event.client_payload.tag_name == steps.latest-octoprint.outputs.release }}
            canary::${{ github.event.action == 'canary' }}
            bleeding::${{ github.event.action == 'bleeding' }}
```

This one snippet demonstrates the how i think the approach to tagging should work in ghaction-dockermeta: 
 - explicit control over the conditions of each and every tag, 
- semver parsing
- no interdependent input parameters, 
- output compatible with docker/build-push-action
- supports tag suffixes #15
- supports additional non-semver custom tags #24 via `extra_tags`
- compatible with externally triggered events
- sha tags (via `extra_tags` parameter in a similar way to your `{{raw}}` usage

### Bonus

As far as I can tell, refactoring tag inputs to work as they do in HackerHappyHour/tagging-strategy@v3+ would close the following open issues as well:
- #29 (since the base tag input isn't resolved by the action but passed in by the user, the user can pass in whatever they want)
- #27 (simply changing the order in the `tags` or `extra_tags` of HackerHappyHour/tagging-strategy accomplishes this)
- #25 (you can see in the example above how HackerHappyHour/tagging-strategy already does this)
- #13 (HackerHappyHour/tagging-strategy already supports this, examples [here](https://github.com/marketplace/actions/tagging-strategy#variant),  [here](https://github.com/marketplace/actions/tagging-strategy#from-release-on-external-repository) and in the [testing fixtures](https://github.com/HackerHappyHour/tagging-strategy/blob/master/__tests__/__data__/taggingStrategy.js#L71-L72))

I doubt my action will ever get any users (even though I obviously have a super high opinion of it :smirk: ), but you've got the benefit of having been in the docker action space since actions launched, and the have visibility and reach. I'd love for the work I did to benefit your users and carry over here.

Would you be willing to consider a redesign to bring support for this usage technique?  I'd really love to be able to archive my project and merge it with yours!

**Comment by LongLiveCHIEF** [comment]
@crazy-max what are your thoughts on this?

**Comment by crazy-max** [comment]
@LongLiveCHIEF Sorry for the delay! I like the idea of conditional assignment. I will make a quick review of the current implementation and see if this can fit this project. Keep you in touch.

**Comment by mblaschke** [comment]
Any progress on this? I'm interested in prefix/suffixes as this is would make it possible to use multiple Dockerfiles in one project.

**Comment by LongLiveCHIEF** [comment]
@mblaschke this is fully implemented in https://github.com/marketplace/actions/tagging-strategy, and you could always use that in the meantime until @crazy-max makes a final decision.

It doesn't do label generation, so you'd still need this action if you want labels.

If you want to see some examples of a robust implementation, check out https://github.com/OctoPrint/octoprint-docker/blob/master/.github/workflows/octoprint-release.yml#L160-L174

... there are several examples of all the features in the github.com/OctoPrint/octoprint-docker github actions.

**Comment by crazy-max** [comment]
@LongLiveCHIEF I have started to work in this yesterday. Here is a draft of what I plan to put in place for a v2:

New:

* `tags`
* `labels`

Kept:

* `images`
* `sep-tags`
* `sep-labels`

Removed:

* `tag-sha`
* `tag-edge`
* `tag-edge-branch`
* `tag-semver`
* `tag-match`
* `tag-match-group`
* `tag-latest`
* `tag-schedule`
* `tag-custom`
* `tag-custom-only`
* `label-custom`

## Migration

### `tag-sha`

```yaml
tags: |
  type=sha,enable=true,latest=false,prefix=pr-,suffix=
```

Defaults:

* `enable=false`
* `latest=false`
* `prefix=pr-`
* `suffix=`

### `tag-edge` / `tag-edge-branch`

```yaml
tags: |
  type=edge,enable=true,latest=false,branch=${default_branch}
```

Defaults:

* `enable=false`
* `latest=false`
* `branch=${default_branch}`

### `tag-semver`

```yaml
tags: |
  type=semver,enable=true,latest=true,pattern=,prefix=,suffix=
```

Defaults:

* `enable=true`
* `latest=true`
* `pattern=`
* `prefix=`
* `suffix=`

### `tag-match` / `tag-match-group`

```yaml
tags: |
  type=match,enable=true,latest=true,group=,prefix=,suffix=
```

Defaults:

* `enable=false`
* `latest=true`
* `group=`
* `prefix=`
* `suffix=`

### `tag-latest`

Will be available for all types through `latest=true|false` keypair.

### `tag-schedule`

```yaml
tags: |
  type=schedule,enable=true,latest=false,pattern=,prefix=,suffix=
```

Defaults:

* `enable=false`
* `latest=false`
* `pattern=`
* `prefix=`
* `suffix=`

### `tag-custom` / `tag-custom-only`

```yaml
tags: |
  type=tag,enable=true,latest=false,acustomtag
# or
tags: |
  acustomtag
```

Defaults:

* `enable=false`
* `latest=false`

### `labels`

```yaml
labels: |
  maintainer=CrazyMax
```

## Flavor

### Prefix and suffix a specific tag

```yaml
tags: |
  type=sha,enable=true,latest=false,prefix=foo-,suffix=-bar
```

### Prefix and suffix all tags

```yaml
tags: |
  type=prefix,foo-
  type=suffix,-bar
```

## Optional keys

`enable`, `latest`, `prefix`, `suffix` inputs are optional.
