### ISSUE TITLE
Question: How to retrieve the sha tag for later usage.

### ISSUE THREAD

**Issue by tofran** [crazy-max/ghaction-docker-meta#38]
Thanks for your work,

How do you expect the usage of the commit sha tag in for example a deploy step?

The `outputs.tags` is very useful to docker build, but what's the best way to use the sha tag without interpolations?

```
Docker tags
  regist.ry/app:my-branch
  regist.ry/app:sha-50fb88d
```

I want to use `regist.ry/app:sha-50fb88d` in another step:

```yaml
  - name: Example deploy
    run: deploy **regist.ry/app:sha-50fb88d**
```

Thank you

**Comment by jolestar** [comment]
+1 expect action output sha tag.

**Comment by jolestar** [comment]
A workaround method:

```yaml
- name: Example deploy
run: |
  SHA=$(git rev-parse --short HEAD);
  deploy **regist.ry/app:sha-${SHA}**

```

**Comment by tofran** [comment]
@jolestar thank you for your reply.

I also have a similar workaround.
The workaround seems even more hacky when you need to pass the tag to a separate deploy task, like:

```yaml
 - name: 'Deploy'
   uses: some-org/some-deploy-action@v2
   with: 
     tag:  ${{ needs.build.outputs.image_tag }}
```
