### ISSUE TITLE
It is not possible to reproduce docker-build-push-action@v1 behavior

### ISSUE THREAD

**Issue by vitalyster** [crazy-max/ghaction-docker-meta#40]
### Behaviour
My configuration in V1 was: tag each commit to default branch as 'latest', and tag each git tag (e.g. 'v1.0.0') with v1.0.0 docker tag.
With V2 and this meta action everything is broken: when I push a git tag 'git push v1.0.0' I got 'v1.0.0' and 'latest' docker tags pointing to the same image. When I build an image on default branch without tag - 'latest' tag overwritten and pointing to some wrong image!
#### Steps to reproduce this issue

1. This is my test Github repo with these actions - https://github.com/vitalyster/docker_build_action_hello
2. This is what was published from master branch - https://hub.docker.com/repository/docker/vitalyster/hello/tags?page=1&ordering=last_updated

#### Expected behaviour

'latest' tag should point to '1.0.0' **or** 'master' tag (should be configurable)

#### Actual behaviour

I'm not sure what is going on with latest tag, it is unusable for me

**Comment by crazy-max** [comment]
@vitalyster 

> tag each commit to default branch as 'latest'

Not really a best practice, latest tag should always point to a semver release. But if you really want this you can use:

```yaml
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app
          tag-semver: |
            {{version}}
          tag-latest: ${{ endsWith(github.ref, github.repository.default_branch) || startsWith(github.ref, 'refs/tags/') }}
```

**Comment by vitalyster** [comment]
I pushed these changes to my test repo and behavior still wrong: only `master` tag is updated, `latest` tag still broken

**Comment by vitalyster** [comment]
And I'm OK if `latest` will point to latest server release, but now it pointing nowhere

**Comment by crazy-max** [comment]
@vitalyster In that case you can simply use use:

```yaml
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app
          tag-semver: |
            {{version}}
```
