### ISSUE TITLE
Is there a variable for branch?

### ISSUE THREAD

**Issue by ekristen** [crazy-max/ghaction-docker-meta#60]
Is there a way to do the branch name dynamically as the prefix?

```
type=sha,prefix=${{ branch_name}}-,suffix=,enable=true
```

Something like that ^

**Comment by crazy-max** [comment]
@ekristen 

> Is there a way to do the branch name dynamically as the prefix?

Not currently but we could support a global [Handlebars template](https://handlebarsjs.com/guide/) on prefix,suffix,value attributes. In the meantime you can do this:

```yaml
steps:
  -
    name: Prepare
    id: prep
    run: |
      echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
  -
    name: Docker meta
    id: meta
    uses: crazy-max/ghaction-docker-meta@v2
    with:
      images: name/app
      tags: |
        type=sha,prefix=${{ steps.prep.outputs.branch }}-,suffix=,enable=true
```

**Comment by monkbroc** [comment]
I was looking for `${branch}-${sha}` as the tag name and instead of settting the branch name as a prefix I ended up setting the SHA as a suffix so the rest of the `type=ref,event=branch` logic will apply.

```
      - name: Set short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch,suffix=-${{ steps.vars.outputs.sha_short }}
```
