### ISSUE TITLE
Unless you have tag-match set, tag-match-latest does nothing on tag push.

### ISSUE THREAD

**Issue by Zageron** [crazy-max/ghaction-docker-meta#7]
#### Steps to reproduce this issue

1. Set `tag-match-latest: false` without `tag-match`.
2. Push a new tag
3. Observe meta output includes latest tag.

#### Expected behaviour

> Latest tag should be disableable without settings `tag-match`.

#### Actual behaviour

> Latest tag is set when I wanted it to not be set.

```yml
name: Build Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}/web-noteskin-editor
          tag-sha: true
          tag-match-latest: false
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

```

### Logs

```bash
Docker tags
  flashflashrevolution/web-noteskin-editor/web-noteskin-editor:v0.0.1
  flashflashrevolution/web-noteskin-editor/web-noteskin-editor:latest
  flashflashrevolution/web-noteskin-editor/web-noteskin-editor:sha-f7fda8a
```

### Note

The following config works as expected.

```yaml
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}/web-noteskin-editor
          tag-match: v(.*)
          tag-sha: true
          tag-match-latest: false
```
