### ISSUE TITLE
Semver shouldnt publish tag `0`

### ISSUE THREAD

**Issue by EdJoPaTo** [crazy-max/ghaction-docker-meta#70]
### Behaviour

Semver version `0.2` to `0.3` is breaking the same as `1` to `2`.
Using tag `1` with only minor changes will not be breaking.
Using tag `0` will include breaking changes and should therefore not be used/published. (`latest` is there anyway)
The only benefit of using `0` over `latest` would be to prevent using `1` later on which seems like no benefit.

#### Steps to reproduce this issue

Publish tag `v0.2.3` to a repo with config below.

#### Expected behaviour

Tags `latest`, `0.2` and `0.2.3` should be published.
Tag `0` should not be published.

#### Actual behaviour

Additionally tag `0` is published.

### Configuration

* Repository URL: https://github.com/EdJoPaTo/website-changed-bot
* Generated Builds URL: https://github.com/users/EdJoPaTo/packages/container/website-changed-bot/versions
* Build URL: https://github.com/EdJoPaTo/website-changed-bot/actions/runs/802323515

```yml
uses: crazy-max/ghaction-docker-meta@v2
with:
  tags: |
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}
```

**Comment by crazy-max** [comment]
@EdJoPaTo I agree with the principle but I don't think it's legitimate to treat this pattern in this action. However, you can manage this case on your side:

```yaml
uses: crazy-max/ghaction-docker-meta@v2
with:
  tags: |
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
```
